#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     libtmcsplit
 *     ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint
     no-unused-vars: [
       "error",
       { "vars":
           "local" } ] */

const
  _split_file_module =
    require(
      'split-file');
const
  _split_file =
    _split_file_module._split_file;
const
  _split_file_by_size =
    _split_file_module._split_file_by_size;
const
  _libcrash =
    require(
      'crash-js');
const
  _msg_info =
    _libcrash._msg_info;
const
  _msg_error =
    _libcrash._msg_error;

async function
  _split(
    _input_file,
    _output_prefix,
    _chunks_amount,
    _size_max) {
  let
    _msg;
  const
    _chunks_amount_not_number =
      isNaN(_chunks_amount);
  if ( _chunks_amount_not_number ) {
    _msg =
      "Chunks amount must be a number.";
    _msg_error(
      _msg,
      1);
  }
  _msg =
    `Splitting '${_input_file}' ` +
    `into '${_chunks_amount}' of size '${_size_max}' ` +
    `into files with prefix '${_output_prefix}':`;
  _msg_info(
    _msg);
  _size_max =
    Number(
      _size_max);
  if ( _chunks_amount > 0 ) {
    _split_file(
      _input_file,
      _chunks_amount);
  }
  else if ( _size_max > 0 ) {
    await _split_file_by_size(
      _input_file,
      _size_max);
  }
}

module.exports = {
  _split:
    _split
};
