#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     libtmcsplit
 *     ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint
     no-unused-vars: [
       "error",
       { "vars":
           "local",
         "varsIgnorePattern":
           "_ls" } ] */

const
  _split_file =
  require(
    'split-file');
const
  _libcrash =
  require(
    'crash-js');
const
  _fs_worker_start =
    _libcrash._fs_worker_start;
// _json_read =
//   _libcrash._json_read;
const
  _ls =
    _libcrash._ls;
const
  _mkdir =
    _libcrash._mkdir;
const
  _msg_info =
    _libcrash._msg_info;
// const
//   _msg_error =
//     _libcrash._msg_error;

async function
  _split(
    _input_file,
    _output_prefix,
    _chunks_amount,
    _size_max) {
  let
    _msg;
  const
    _dir =
      "test_dir";
  const
    _file =
      `${_dir}/test_file`;
  // _content =
  //   `${_target_message} ${_target_planet}`;
  // const
  //   _fs_worker_path =
  //     "fs-worker.js";
  // const
  //   _fs_worker =
  //     await _fs_worker_start(
  //         _fs_worker_path);
  console.log(
    _file);
  // console.log(
  //   _fs_worker);
  _msg =
    `Splitting '${_input_file}' ` +
    `into '${_chunks_amount}' of size '${_size_max}'` +
    `into files with prefix '${_output_prefix}':`;
  _msg_info(
    _msg);
  console.log(
    _split_file._split_file);
  _parts_amount_not_number =
    isNaN(_parts_amount);
  if ( _parts_amount_not_number ) {
    return this._usage();
  }
  _split_file_callback =
    _split_file_callback_get();
  _split_file(
    _input_file,
    _parts_amount).then(
    _split_file_callback).catch(
      _error_handle);
  // await _mkdir(
  //   _dir);
  _msg =
    `Downloading a file for testing.`;
  _msg_info(
    _msg);
  // _downloaded_file =
  //   await _file_download(
  //     "")
  // console.log(
  //   _downloaded_file);
  // _msg =
  //   `Writing content '${_content}' to file '${_file}':`;
  // _msg_info(
  //   _msg);
  // _file_write(
  //   _file,
  //   _content);
  // _msg =
  //   `Content of directory '/':`;
  // _msg_info(
  //   _msg);
  // _dir_content =
  //   _ls(
  //     "/").unwrap();
  // console.log(
  //   _dir_content);
  // _msg =
  //   `Content of directory '${_dir}':`;
  // _msg_info(
  //   _msg);
  // _dir_content =
  //   _ls(
  //     _dir).unwrap();
  // console.log(
  //   _dir_content);
}

module.exports = {
  _split:
    _split
};
