#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

//    ----------------------------------------------------------------------
//    Copyright © 2024, 2025  Pellegrino Prevete
//
//    All rights reserved
//    ----------------------------------------------------------------------
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU Affero General Public License for more details.
//
//    You should have received a copy of the GNU Affero General Public License
//    along with this program.  If not, see <https://www.gnu.org/licenses/>.

const
  _libcrash =
  require(
    'crash-js');
_cmdline_check =
  _libcrash._cmdline_check;
_msg_info =
  _libcrash._msg_info;
_msg_error =
  _libcrash._msg_error;
const
  _split_module =
    require(
      "./libtmcsplit");
_tmcsplit =
  _split_module._tmcsplit;

function
  _global_variables() {
  app_name =
    "tmcsplit";
  suffix_length =
    "";
  chunks_amount =
    "";
  string_length =
    "";
  size_max =
    "";
  output_prefix =
    "";
  quiet =
    "";
}

function 
  _overrides_set() {
  if ( suffix_length == "" ) {
    suffix_length =
      "base64";
  }
  if ( output_prefix == "" ) {
    output_prefix =
      _input_file + ".";
  }
}

function
  _config_show() {
  let
    _line,
    _text;
  _text = [
    `${app_name} configuration:`,
    `      Runtime environment:   ${runtime_environment}`,
    `            Suffix length:   ${suffix_length}`,
    `       Maximum chunk size:   ${size_max} bytes`,
    `         Amount of chunks:   ${chunks_amount}`,
    `                  In file:   ${input_file}`,
    `         Out files prefix:   ${output_prefix}`,
  ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line,
    _text;
  _text = [
    "Output pieces of FILE to PREFIXaa, PREFIXab, ...",
    "default size is 1000 lines, and default PREFIX is 'x'.",
    "",
    "Usage:",
    "",
    "  tmcsplit",
    "    <in-file>",
    "    <out-txt-prefix>",
    "",
    "  arguments:",
    "    <in-file>                        An input file.",
    "    <out-file-prefix>                Prefix for the output file(s).",
    "",
    "  options:",
    "",
    "     -a, --suffix-length=N           Generate suffixes of length N",
    `                                     Default: '${suffix_length}'`,
    "     --additional-suffix=SUFFIX      append an additional SUFFIX",
    "                                     to file names",
    "     -b, --bytes=SIZE                Put SIZE bytes per output file",
    "     -C, --line-bytes=SIZE           Put at most SIZE bytes of",
    "                                     records per output file.",
    "     -d                              Use numeric suffixes starting",
    "                                     at 0, not alphabetic",
    "     --numeric-suffixes[=FROM]       Same as -d, but allow setting",
    "                                     the start value.",
    "     -l, --lines=NUMBER              Put NUMBER lines/records per",
    "                                     output file.",
    "     -n, --number=CHUNKS             Generate CHUNKS output files;",
    "                                     see explanation below",
    "     -t, --separator=SEP             Use SEP instead of newline as",
    "                                     the record separator;",
    "                                     '\0' (zero) specifies the",
    "                                     NUL character.",
    "",
    "     -h --help                       This message.",
    "     -v --verbose                    Enable verbose output.",
    "",
    "The SIZE argument is an integer and optional",
    "unit (example: 10K is 10*1024).",
    "Units are K,M,G,T,P,E,Z,Y,R,Q (powers of 1024)",
    "or KB,MB,... (powers of 1000).",
    "Binary prefixes can be used, too: KiB=K, MiB=M, and so on.",
    "",
    "CHUNKS may be:",
    "  N       split into N files based on size of input",
    "  K/N     output Kth of N to standard output",
    "  l/N     split into N files without splitting lines/records",
    "  l/K/N   output Kth of N to standard output without",
    "          splitting lines/records",
  ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
  process.exit(
    _exit_code);
}

function
  _cmdline_parse_help(
    _argv) {
  let
    _help_display;
  _help_display =
    _argv[
      "help"] ||
    _argv[
      "h"];
  if ( _help_display ) {
    quiet =
      "n";
    _usage(
      0);
  }
}

function
  _input_args_check(
    _argv) {
  if ( _argv[
         "_"].length < 1 ) {
    _msg =
      "Input file argument required.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
}

function 
  _cmdline_parse() {
  let
    _argv,
    _msg;
  _argv =
    _yargv_get();
  quiet = 
    "y";
  runtime_environment =
    "node";
  _cmdline_parse_help(
    _argv);
  _input_args_check(
    _argv);
  input_file =
    _argv[
      "_"][
        0];
  if ( _argv[
         "_"].length < 2 ) {
    output_prefix =
      input_file + "."
  }
  if ( "a" in _argv ) {
    suffix_length =
      _argv[
        "a"];
  }
  if ( "suffix-length" in _argv ) {
    suffix_length =
      _argv[
        "suffix-length"];
  }
  chunks_amount =
    _argv[
      "chunks-amount"] ||
    _argv[
      "n"];
  chunks_amount =
    _argv[
      "size-max"] ||
    _argv[
      "b"];
  verbose =
    _argv[
      "verbose"] ||
    _argv[
      "v"];
  if ( verbose ) {
    quiet =
      "n";
  }
}

function
  _url_parse() {
  let
    _argv;
  runtime_environment =
    "browser";
  _argv =
    _argv_url_get();
  input_file =
    _argv_url_get(
      "input_file")[
        0];
  output_prefix =
    _argv_url_get(
      "output_prefix")[
        0];
  chunks_amount =
    _argv_url_get(
      "chunks_amount")[
        0];
  quiet =
    _argv_url_get(
      "quiet");
  if ( quiet.length === 0 ) {
    quiet =
      "n";
  }
}

_global_variables();
if ( _cmdline_check(
       "tmcsplit") == true ) {
  _cmdline_parse();
}
else {
  _url_parse();
}
_config_show();
app_opts = [
  input_file,
  output_prefix,
  chunks_amount,
  size_max
];
_tmcsplit.apply(
  null,
  app_opts);
