#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     tmcsplit
 *     ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint
     no-unused-vars: [
       "error",
       { "vars":
           "local",
         "argsIgnorePattern":
           "output_prefix" } ] */

const
  _libcrash =
    require(
      'crash-js');
/* global
     _argv_url_get */
const
_argv_url_get =
  _libcrash._argv_url_get;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
_msg_error =
  _libcrash._msg_error;
/* global
     _yargv_get */
const
_yargv_get =
  _libcrash._yargv_get;
const
  _split_module =
    require(
      "./libtmcsplit");
/* global
     _tmcsplit */
const
  _tmcsplit =
    _split_module._tmcsplit;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  app_name =
    "tmcsplit";
  /* global
       app_opts:
         writable */
  app_opts =
    [];
  /* global
       runtime_environment:
         writable */
  runtime_environment =
    "";
  /* global
       suffix_length:
         writable */
  suffix_length =
    "";
  /* global
       chunks_amount:
         writable */
  chunks_amount =
    "";
  // string_length =
  //   "";
  /* global
       size_max:
         writable */
  size_max =
    "";
  /* global
       input_file:
         writable */
  input_file =
    "";
  /* global
       output_prefix:
         writable */
  output_prefix =
    "";
  /* global
       quiet:
         writable */
  quiet =
    "";
  /* global
       verbose:
         writable */
  verbose =
    "";
}

function 
  _overrides_set() {
  if ( suffix_length == "" ) {
    suffix_length =
      "base64";
  }
  if ( output_prefix == "" ) {
    output_prefix =
      input_file + ".";
  }
}

function
  _config_show() {
  let
    _line;
  const
    _text = [
      `${app_name} configuration:`,
      `      Runtime environment:   ${runtime_environment}`,
      `            Suffix length:   ${suffix_length}`,
      `       Maximum chunk size:   ${size_max} bytes`,
      `         Amount of chunks:   ${chunks_amount}`,
      `                  In file:   ${input_file}`,
      `         Out files prefix:   ${output_prefix}`,
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _text = [
      "Output pieces of FILE to PREFIXaa, PREFIXab, ...",
      "default size is 1000 lines, and default PREFIX is 'x'.",
      "",
      "Usage:",
      "",
      "  tmcsplit",
      "    <in-file>",
      "    <out-txt-prefix>",
      "",
      "  arguments:",
      "    <in-file>                      An input file.",
      "    <out-file-prefix>              Prefix for the output",
      "                                   file(s).",
      "",
      "  options:",
      "",
      "     -a, --suffix-length=N         Generate suffixes of",
      "                                   length N.",
      `                                   Default: '${suffix_length}'`,
      "     --additional-suffix=SUFFIX    append an additional SUFFIX",
      "                                   to file names.",
      "     -b, --bytes=SIZE              Put SIZE bytes per output",
      "                                   file.",
      "     -C, --line-bytes=SIZE         Put at most SIZE bytes of",
      "                                   records per output file.",
      "     -d                            Use numeric suffixes",
      "                                   starting at 0, not",
      "                                   alphabetic.",
      "     --numeric-suffixes[=FROM]     Same as -d, but allow",
      "                                   setting the start value.",
      "     -l, --lines=NUMBER            Put NUMBER lines/records",
      "                                   per output file.",
      "     -n, --number=CHUNKS           Generate CHUNKS output",
      "                                   files; see explanation",
      "                                   below",
      "     -t, --separator=SEP           Use SEP instead of newline",
      "                                   as the record separator;",
      "                                   '\0' (zero) specifies the",
      "                                   NUL character.",
      "",
      "     -h --help                     This message.",
      "     -v --verbose                  Enable verbose output.",
      "",
      "The SIZE argument is an integer and optional",
      "unit (example: 10K is 10*1024).",
      "Units are K,M,G,T,P,E,Z,Y,R,Q (powers of 1024)",
      "or KB,MB,... (powers of 1000).",
      "Binary prefixes can be used, too: KiB=K, MiB=M, and so on.",
      "",
      "CHUNKS may be:",
      "  N       split into N files based on size of input",
      "  K/N     output Kth of N to standard output",
      "  l/N     split into N files without splitting lines/records",
      "  l/K/N   output Kth of N to standard output without",
      "          splitting lines/records",
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
  process.exit(
    _exit_code);
}

function
  _cmdline_parse_help(
    _argv) {
  const
    _help_display =
      _argv[
        "help"] ||
      _argv[
        "h"];
  if ( _help_display ) {
    quiet =
      "n";
    _usage(
      0);
  }
}

function
  _input_args_check(
    _argv) {
  if ( _argv[
         "_"].length < 1 ) {
    const
      _msg =
        "Input file argument required.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
}

function 
  _cmdline_parse() {
  const
    _argv =
      _yargv_get();
  quiet = 
    "y";
  runtime_environment =
    "node";
  _cmdline_parse_help(
    _argv);
  _input_args_check(
    _argv);
  input_file =
    _argv[
      "_"][
        0];
  if ( _argv[
         "_"].length < 2 ) {
    output_prefix =
      `${input_file}.`;
  }
  if ( "a" in _argv ) {
    suffix_length =
      _argv[
        "a"];
  }
  if ( "suffix-length" in _argv ) {
    suffix_length =
      _argv[
        "suffix-length"];
  }
  chunks_amount =
    _argv[
      "chunks-amount"] ||
    _argv[
      "n"];
  chunks_amount =
    _argv[
      "size-max"] ||
    _argv[
      "b"];
  verbose =
    _argv[
      "verbose"] ||
    _argv[
      "v"];
  if ( verbose ) {
    quiet =
      "n";
  }
}

function
  _url_parse() {
  const
    _argv =
      _argv_url_get();
  runtime_environment =
    "browser";
  input_file =
    _argv[
      "input_file"][
        0];
  output_prefix =
    _argv_url_get[
      "output_prefix"][
        0];
  chunks_amount =
    _argv_url_get[
      "chunks_amount"][
        0];
  quiet =
    _argv_url_get[
      "quiet"];
  if ( quiet.length === 0 ) {
    quiet =
      "n";
  }
}

_global_variables();
_overrides_set();
if ( _cmdline_check(
       "tmcsplit") == true ) {
  _cmdline_parse();
}
else {
  _url_parse();
}
_config_show();
app_opts = [
  input_file,
  output_prefix,
  chunks_amount,
  size_max
];
_tmcsplit.apply(
  null,
  app_opts);
